In [1]:
#importing the libraries
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import re

In [2]:
cities = ["Ahmedabad","Bangalore","Chennai","Delhi","Faridabad","Ghaziabad","Gurgaon","Hyderabad","Jaipur","Mumbai","Noida","Pune"]

In [3]:
# Analyzing the urls and adding beautifulsoup library to scrape the data 
url = f"https://ackodrive.com/collection/car-offers/{cities}/"
page =  requests.get(url).text
soup = BeautifulSoup(page,"lxml")

In [4]:
# creating lists to store the scraped data 
brands = []
models = []
body = []
variant = []
fuel_type = []
transmission = []
city = []
price = []
discount = []
mileage = []
engine_power = []

In [5]:
cities = ["Ahmedabad","Bangalore","Chennai","Delhi","Faridabad","Ghaziabad","Gurgaon","Hyderabad","Jaipur","Mumbai","Noida","Pune"]

# Scraping the data based on hot deals of city

In [6]:
for region in cities:
    url = f"https://ackodrive.com/collection/car-offers/{region}/"
    page =  requests.get(url).text
    soup = BeautifulSoup(page,"lxml")
    
    # extracting the car brands 
    for i in soup.find_all("span", class_ = "styles__Make-sc-aa3bd0b2-5 dQwQsS"):
        if i.text:
            brands.append(i.text)
        else:
            brands.append(np.nan)
            
     # extracting the car models   
    for i in soup.find_all("span", class_= "styles__ModelName-sc-aa3bd0b2-6 lhqRyF"):
        if i.text:
            models.append(i.text)
        else:
            models.append(np.nan)

    # extracting car body type
    for i in soup.find_all("div",class_ = "styles__ModelInfo-sc-aa3bd0b2-8 cEyrJI"):
        body_type = re.findall(r"^\w+",i.text,re.MULTILINE)
        if body_type:
            body.append(body_type[0])
        else:
            body.append(np.nan)

    #extracting the car variants    
    for i in soup.find_all("h4", class_ = "styles__VariantTitle-sc-aa3bd0b2-10 kqHbXK"):
        if i.text:
            variant.append(i.text)
        else:
            variant.append(np.nan)
    
    # extracting the fuel and transmisison type 
    
    s1 = soup.find_all("div", class_="styles__VariantInfo-sc-aa3bd0b2-12 kCNdrj")
    for div in s1:
        for i in div.find_all("p", class_="styles__ParaWithoutMargins-sc-aa3bd0b2-34 hVfpJl")[0]:
            if i.text:
                fuel_type.append(i.text)
            else:
                fuel_type.append(np.nan)
            
        for i in div.find_all("p", class_="styles__ParaWithoutMargins-sc-aa3bd0b2-34 hVfpJl")[1]:
            if i.text:
                transmission.append(i.text)
            else:
                transmission.append(np.nan)
    
    # extracting city 
    
    for i in soup.find_all("div", class_ = "styles__CityName-sc-aa3bd0b2-17 bysq"):
        text = re.findall(r"\s.+",i.text)
        city.append(text[0])
        
    # extracting price
    for i in soup.find_all("div", class_ = "styles__Price-sc-aa3bd0b2-18 bzmdsn"):
        price_extract = re.findall(r"\d+(?:\.\d+)?",i.text)
        price.append(price_extract[0])



    # extracting the specifications 
    
    specification_links = []  
    
    # Iterate through all cars and extract specification links
    for car in soup.find_all('div', class_='styles__ModelSection-sc-8077a65d-1 hKUHxq'): 
        # Find the <a> tag with the href attribute
        link_tag = car.find('a', href=True)
        if link_tag:
            spec_link = link_tag['href']
            specification_links.append(f"{spec_link}/specifications")
        else:
            print("No link found for this car.")
    
    
    for link in specification_links:
        try:
            html_data = requests.get(link).text
            s1 = BeautifulSoup(html_data, "lxml")
    
            # Find all spans with the specific class
            spans = s1.find_all("span", class_="specsAndFeatures__SpecItemValue-sc-7c88d2e9-16 dycqwB")
    
            # Check if the first span (mileage) exists
            if len(spans) > 0:
                mileage_text = spans[0].text.strip() if spans[0].text else np.nan
                mileage.append(mileage_text)
            else:
                print(f"No mileage data found on page: {link}")
                mileage.append(np.nan)
    
            # Check if the second span (power) exists
            if len(spans) > 1:
                power_text = spans[1].text.strip() if spans[1].text else np.nan
                engine_power.append(power_text)
            else:
                print(f"No power data found on page: {link}")
                engine_power.append(np.nan)
    
        except Exception as e:
            print(f"Error occurred while processing {link}: {e}")
            mileage.append(np.nan)
            engine_power.append(np.nan)

No mileage data found on page: https://ackodrive.com/cars/hyundai-creta//specifications
No power data found on page: https://ackodrive.com/cars/hyundai-creta//specifications

In [7]:
print(len(brands))
print(len(models))
print(len(body))
print(len(variant))
print(len(fuel_type))
print(len(transmission))
print(len(city))
print(len(price))
print(len(mileage))
print(len(engine_power))

113
113
113
113
113
113
113
113
113
113

In [8]:
brands_1 = []
models_1 = []
body_1 = []
variant_1 = []
fuel_type1 = []
transmission_1 = []
city_1 = []
price_1 = []
discount_1 = []
mileage_1 = []
engine_power1 = []

In [9]:
brand = ["toyota","tata","maruti","mahindra","hyundai","renault","volkswagen","kia","honda","audi","jaguar"]
cities = ["Ahmedabad","Bangalore","Chennai","Delhi","Faridabad","Ghaziabad","Gurgaon","Hyderabad","Jaipur","Mumbai","Noida","Pune"]

In [10]:
import itertools

In [11]:
for bran, region in itertools.product(brand,cities):
    url = f"https://ackodrive.com/collection/{bran}-cars/{region}/"
    page =  requests.get(url).text
    soup = BeautifulSoup(page,"lxml")
    

    for i in soup.find_all("span", class_ = "styles__Make-sc-aa3bd0b2-5 dQwQsS"):
        if i.text:
            brands_1.append(i.text)
        else:
            brands_1.append(np.nan)
        
    for i in soup.find_all("span", class_= "styles__ModelName-sc-aa3bd0b2-6 lhqRyF"):
        if i.text:
            models_1.append(i.text)
        else:
            models_1.append(np.nan)

    for i in soup.find_all("div",class_ = "styles__ModelInfo-sc-aa3bd0b2-8 cEyrJI"):
        body_type = re.findall(r"^\w+",i.text,re.MULTILINE)
        if body_type:
            body_1.append(body_type[0])
        else:
            body_1.append(np.nan)
        
    for i in soup.find_all("h4", class_ = "styles__VariantTitle-sc-aa3bd0b2-10 kqHbXK"):
        if i.text:
            variant_1.append(i.text)
        else:
            variant_1.append(np.nan)
    
    # extracting the fuel and transmisison type 
    
    s1 = soup.find_all("div", class_="styles__VariantInfo-sc-aa3bd0b2-12 kCNdrj")
    for div in s1:
        for i in div.find_all("p", class_="styles__ParaWithoutMargins-sc-aa3bd0b2-34 hVfpJl")[0]:
            if i.text:
                fuel_type1.append(i.text)
            else:
                fuel_type1.append(np.nan)
            
        for i in div.find_all("p", class_="styles__ParaWithoutMargins-sc-aa3bd0b2-34 hVfpJl")[1]:
            if i.text:
                transmission_1.append(i.text)
            else:
                transmission_1.append(np.nan)
    
    # extracting city 
    
    for i in soup.find_all("div", class_ = "styles__CityName-sc-aa3bd0b2-17 bysq"):
        text = re.findall(r"\s.+",i.text)
        city_1.append(text[0])
        
    # extracting price
    for i in soup.find_all("div", class_ = "styles__Price-sc-aa3bd0b2-18 bzmdsn"):
        price_extract = re.findall(r"\d+(?:\.\d+)?",i.text)
        price_1.append(price_extract[0])



    # extracting the specifications 
    
    specification_links = []  
    
    # Iterate through all cars and extract specification links
    for car in soup.find_all('div', class_='styles__ModelSection-sc-8077a65d-1 hKUHxq'): 
        # Find the <a> tag with the href attribute
        link_tag = car.find('a', href=True)
        if link_tag:
            spec_link = link_tag['href']
            specification_links.append(f"{spec_link}/specifications")
        else:
            print("No link found for this car.")

    for link in specification_links:
        try:
            html_data = requests.get(link).text
            s1 = BeautifulSoup(html_data, "lxml")
    
            # Find all spans with the specific class
            spans = s1.find_all("span", class_="specsAndFeatures__SpecItemValue-sc-7c88d2e9-16 dycqwB")
    
            # Check if the first span (mileage) exists
            if len(spans) > 0:
                mileage_text = spans[0].text.strip() if spans[0].text else np.nan
                mileage_1.append(mileage_text)
            else:
                print(f"No mileage data found on page: {link}")
                mileage_1.append(np.nan)
    
            # Check if the second span (power) exists
            if len(spans) > 1:
                power_text = spans[1].text.strip() if spans[1].text else np.nan
                engine_power1.append(power_text)
            else:
                print(f"No power data found on page: {link}")
                engine_power1.append(np.nan)
    
        except Exception as e:
            print(f"Error occurred while processing {link}: {e}")
            mileage.append(np.nan)
            engine_power1.append(np.nan)

No mileage data found on page: https://ackodrive.com/cars/toyota-glanza//specifications
No power data found on page: https://ackodrive.com/cars/toyota-glanza//specifications
No mileage data found on page: https://ackodrive.com/cars/tata-tigor//specifications
No power data found on page: https://ackodrive.com/cars/tata-tigor//specifications
No mileage data found on page: https://ackodrive.com/cars/tata-tiago-ev-2022-2025//specifications
No power data found on page: https://ackodrive.com/cars/tata-tiago-ev-2022-2025//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No mileage data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications
No power data found on page: https://ackodrive.com/cars/audi-e-tron-gt//specifications

In [12]:
print(len(brands_1))
print(len(models_1))
print(len(body_1))
print(len(variant_1))
print(len(fuel_type1))
print(len(transmission_1))
print(len(city_1))
print(len(price_1))
print(len(mileage_1))
print(len(engine_power1))

1229
1229
1229
1229
1229
1229
1229
1229
1229
1229

In [13]:
# concating all the lists

In [14]:
car_brands =brands + brands_1
car_models = models + models_1
car_body = body + body_1
car_variant= variant + variant_1 
car_fuel = fuel_type + fuel_type1 
car_transmission = transmission + transmission_1
car_city = city + city_1
car_price = price +price_1
car_mileage = mileage + mileage_1
car_engine_power = engine_power + engine_power1

In [15]:
print(len(car_brands))
print(len(car_models))
print(len(car_body))
print(len(car_variant))
print(len(car_fuel))
print(len(car_transmission))
print(len(car_city))
print(len(car_price))
print(len(car_mileage))
print(len(car_engine_power))

1342
1342
1342
1342
1342
1342
1342
1342
1342
1342

In [16]:
# creating a dataframe
data = pd.DataFrame({"brands": car_brands,"models":car_models,"body" : car_body, "variant": car_variant,"fuel":car_fuel,"transmission":car_transmission,
                     "city":car_city,"price":car_price,"mileage":car_mileage,"engine_power":car_engine_power})

In [17]:
data

,brands,models,body,variant,fuel,transmission,city,price,mileage,engine_power
0,Mahindra,XUV700,SUV7,2.0 MX (E),Petrol,Manual,Bangalore,18.26,12.00 Km/l,1997 cc
1,Hyundai,Verna,Sedan5,1.5 SX IVT,Petrol,Automatic,Bangalore,18.19,25.00 Km/l,1497 cc
2,Hyundai,Exter,SUV5,1.2 S AMT,Petrol,Automatic,Bangalore,10.22,19.40 Km/l,1197 cc
3,Toyota,Urban Cruiser Hyryder,SUV5,Neodrive S,Petrol,Manual,Bangalore,15.94,21.12 Km/l,1462 cc
4,Hyundai,Venue,SUV5,1.2 S(O),Petrol,Manual,Bangalore,12.12,17.52 Km/l,1197 cc
...,...,...,...,...,...,...,...,...,...,...
1337,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Mumbai,1.30,470.00 Km/full charge,90000 watt
1338,Jaguar,F-Pace,SUV5,S R-Dynamic 2.0 Petrol,Petrol,Automatic,Noida,82.66,12.90 Km/l,1997 cc
1339,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Noida,1.30,470.00 Km/full charge,90000 watt
1340,Jaguar,F-Pace,SUV5,S R-Dynamic 2.0 Petrol,Petrol,Automatic,Pune,84.85,12.90 Km/l,1997 cc
1341,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Pune,1.30,470.00 Km/full charge,90000 watt

In [18]:
# storing the data frame to csv
data.to_csv(r"C:\Users\chand\OneDrive\Desktop\acko_Data.csv", index = False)

In [19]:
# loading the csv
df = pd.read_csv(r"C:\Users\chand\OneDrive\Desktop\acko_Data.csv")

In [20]:
df

,brands,models,body,variant,fuel,transmission,city,price,mileage,engine_power
0,Mahindra,XUV700,SUV7,2.0 MX (E),Petrol,Manual,Bangalore,18.26,12.00 Km/l,1997 cc
1,Hyundai,Verna,Sedan5,1.5 SX IVT,Petrol,Automatic,Bangalore,18.19,25.00 Km/l,1497 cc
2,Hyundai,Exter,SUV5,1.2 S AMT,Petrol,Automatic,Bangalore,10.22,19.40 Km/l,1197 cc
3,Toyota,Urban Cruiser Hyryder,SUV5,Neodrive S,Petrol,Manual,Bangalore,15.94,21.12 Km/l,1462 cc
4,Hyundai,Venue,SUV5,1.2 S(O),Petrol,Manual,Bangalore,12.12,17.52 Km/l,1197 cc
...,...,...,...,...,...,...,...,...,...,...
1337,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Mumbai,1.30,470.00 Km/full charge,90000 watt
1338,Jaguar,F-Pace,SUV5,S R-Dynamic 2.0 Petrol,Petrol,Automatic,Noida,82.66,12.90 Km/l,1997 cc
1339,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Noida,1.30,470.00 Km/full charge,90000 watt
1340,Jaguar,F-Pace,SUV5,S R-Dynamic 2.0 Petrol,Petrol,Automatic,Pune,84.85,12.90 Km/l,1997 cc
1341,Jaguar,I-Pace,Coupe2,HSE,Electric,Automatic,Pune,1.30,470.00 Km/full charge,90000 watt